name: Deploy to GitHub Pages.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'build'
      - .git

jobs:
  Build_the_markup_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - name: Install ruby dependencies
        run: bundle install
      - name: Build static site
        run: bundle exec middleman build  
      - name: checkout destination
        run: |
           mkdir dest && cd dest
           git clone https://github.com/P0C2-demo/P0C2-demo.github.io.git
      - name: Check for changes
        id: check_changes
        run: |
             cd src/mtd-itsa-vendors-roadmap/build
             if git diff --exit-code --quiet .; then
               echo "No changes found"  
             fi
      - name: Retrieve markup files
        if: steps.check_changes.outputs.result != 'No changes found'        
        run: |         
            cp -r src/mtd-itsa-vendors-roadmap/build/*  dest/P0C2-demo.github.io/
            cd dest/P0C2-demo.github.io
            git config user.name "Github.Action"
            git config user.email "deliverablestangible@gmail.com"
            git add .
            git commit -m "Deploy to GitHub Pages"               
            git push https://${{ secrets.PAT2 }}@github.com/P0C2-demo/P0C2-demo.github.io.git
