name: Deploy to GitHub Pages.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'build'
      - .git
  workflow_dispatch:
    inputs:
     tags:
      description: 'Manual'
jobs:
  Build_the_markup_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false
      - name: Checkout guide
        run: |
          mkdir src && cd src
          git clone https://github.com/P0C-demo/mtd-itsa-vendors-roadmap.git      
      - name: Install ruby dependencies
        run: |
          cd src/mtd-itsa-vendors-roadmap
          bundle install
      - name: Build static site
        run: |
           cd src/mtd-itsa-vendors-roadmap
           bundle exec middleman build  
      - name: checkout destination
        run: |
           mkdir dest && cd dest
           git clone https://github.com/P0C2-demo/P0C2-demo.github.io.git
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code --quiet .; then
            echo "No changes found"  
            echo "changes=false" >> "$GITHUB_ENV"
          else
            echo "changes=true" >> "$GITHUB_ENV"
          fi
          echo ${{ steps.check_changes.changes }}

      - name: Retrieve markup files
        if:  ${{ steps.check_changes.changes }} == 'true'       
        run: |         
            cp -r src/mtd-itsa-vendors-roadmap/build/*  dest/P0C2-demo.github.io/
            cd dest/P0C2-demo.github.io
            git config user.name "Github.Action"
            git config user.email "deliverablestangible@gmail.com"
            git add .
            git commit -m "Deploy to GitHub Pages"               
            git push https://${{ secrets.PAT2 }}@github.com/P0C2-demo/P0C2-demo.github.io.git
